### ISSUE TITLE
Trajopt has a position error of 1cm and 7cm along x and y axis pose

### ISSUE THREAD

**Issue by lakshmip001** [ros-industrial-consortium/trajopt_ros#91] opened 2019-03-01 05:45 UTC
I am moving to a cartesian pose using trajopt which results in an error of 1cm and 7cm along pose_x and pose_y . Can I solve this by increasing the costs in pos_coeffs and rot_coeffs. What are the maximum and minimum values for pos_coeffs and rot_coeffs. And to move to the exact position , do I need to vary other variables.

pose_constraint->xyz = start_pose.translation() + xyz_delta * i;

            Quaterniond rotation_delta(cos(0.5 * angle_delta * i),
                                       delta_axis.x() * sin(0.5 * angle_delta * i),
                                       delta_axis.y() * sin(0.5 * angle_delta * i),
                                       delta_axis.z() * sin(0.5 * angle_delta * i));
            Quaterniond rotation = rotation_delta * approach_rotation;

            /* Fill Code:
                 . Set the pose rotation
                 . Set pos_coeffs to all 10s
                 . Set rot_coeffs to all 10s
                 . Define the pose name as pose_[timestep]
                 . pushback the constraint to cnt_infos
            */
            /* ========  ENTER CODE HERE ======== */
            pose_constraint->wxyz = Vector4d(rotation.w(), rotation.x(), rotation.y(), rotation.z());
            std::cout <<"pose_xyz" << pose_constraint->xyz << "pose_wxyz" << pose_constraint->wxyz << std::endl;
            pose_constraint->pos_coeffs = Vector3d(50.0, 50.0, 50.0);
            pose_constraint->rot_coeffs = Vector3d(50.0, 50.0, 50.0);
            pose_constraint->name = "pose_" + std::to_string(i + first_time_step);
Do I need to work with optimiziers.cpp to reach better end_pose in the following variables?

 improve_ratio_threshold = 0.025;
  min_trust_box_size = 1e-7;
  min_approx_improve = 1e-7;
  min_approx_improve_frac = -INFINITY;
  max_iter = 100;
  trust_shrink_ratio = 0.1;
  trust_expand_ratio = 1.5;
  cnt_tolerance = 1e-7;
  max_merit_coeff_increases = 5;
  merit_coeff_increase_ratio = 10;
  max_time = INFINITY;
  merit_error_coeff = 10;
  trust_box_size = 1e-7;

**Comment by mpowelson** [comment] 2019-03-04 13:38
There are no max and min to the coeffs. They just scale the cost. I suppose at some point the cost will overflow if you make it too big, but I'd say as long as you're reasonable it should be fine. Unless you write some custom cost with extreme units, I'd say anything above 100 and I'd be suspicious something else is wrong. In my experience when the problem is set up well (no constraints infeasible) the solution has usually converged to something pretty intuitive regardless of the coeffs.

**Comment by lakshmip001** [comment] 2019-03-04 13:46
Actually solution gives an output that it is converged but when I see the position it reaches has a difference of 10cm along x-axis and 7cm y-axis. How can I make it to reach my end_pose with less error and if there would error in the position what can be the minimum error that I can minimise too. 

I feel the error is because trajopt tries to find the closestfeasiblesolution in a box and if it doesn't find trajopt increases the box size. If these is correct . There can be error existing in most of the end_poses which always doesn't reach its end point correctly. So there might be trajectory tracing to through the end_pose to move to the nextpoint .

**Comment by mpowelson** [comment] 2019-09-20 19:44
I'm going to close this. If you are still needing more information or having the issue, feel free to reopen it.

**Closed by mpowelson** 2019-09-20 19:44 UTC
Labels: question
